<?php
$form->prepare();
$escapeHtml = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate(' Create Tree By Linked Resource form'), 1, $this->translate('Resource Tree')); ?>

<?php echo $this->form()->openTag($form); ?>
<fieldset id='page-actions'>
    <button type="submit"><?php echo $this->translate('Submit'); ?></button>
</fieldset>
Create Tree by Linked Resource
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag($form); ?>